"""
FastAPI wrapper — exposes the full agent system as REST endpoints.

Run: uvicorn api:app --reload --port 8000
Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import Optional
import os
from datetime import datetime, timedelta, timezone

from orchestrator import SessionOrchestrator, LoopState
from progress_tracking_agent import get_dashboard_summary, get_mastery_trend
from planner_agent import build_roadmap
from memory_agent import get_learning_style, set_learning_style, get_mastery, _session, TopicMastery, ErrorEvent, StudentProfile
from syllabus_parser import parse_and_save
from curriculum_mapping_agent import _load_graph

app = FastAPI(title="Adaptive Tutoring API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to your frontend's origin before shipping
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory session store: {session_id: SessionOrchestrator}
# Swap for Redis if you need multi-process/horizontal scaling.
_sessions: dict[str, SessionOrchestrator] = {}
_placement_tests: dict[str, dict] = {}


# ---------- Request/response models ----------

class StartSessionRequest(BaseModel):
    student_id: str
    question: str
    student_answer: str
    correct_answer: str
    topic_hint: Optional[str] = None


class SubmitAnswerRequest(BaseModel):
    session_id: str
    student_response: str


class SetLearningStyleRequest(BaseModel):
    student_id: str
    style: str  # analogy|visual|worked_example|socratic


class RoadmapRequest(BaseModel):
    student_id: str
    mastery_map: dict[str, float]
    days_remaining: int


class SyllabusTextRequest(BaseModel):
    text: str


class SubmitPlacementRequest(BaseModel):
    test_id: str
    answers: dict[str, str]


# ---------- Session lifecycle ----------

@app.post("/session/start")
def start_session(req: StartSessionRequest):
    """
    Kicks off the loop: runs DIAGNOSE -> TEACH -> QUIZ, then pauses and
    returns the generated quiz question, waiting for the student's answer.
    """
    orch = SessionOrchestrator(
        student_id=req.student_id,
        question=req.question,
        student_answer=req.student_answer,
        correct_answer=req.correct_answer,
        topic_hint=req.topic_hint,
    )
    session_id = f"{req.student_id}_{id(orch)}"
    _sessions[session_id] = orch

    # Run until we hit EVALUATE (i.e. a quiz question is ready for the student)
    while orch.state != LoopState.EVALUATE and orch.state != LoopState.DONE:
        orch.step()

    return {
        "session_id": session_id,
        "state": orch.state.name,
        "diagnosis": orch.context.get("diagnosis"),
        "curriculum_info": orch.context.get("curriculum_info"),
        "teach": orch.context.get("last_teach_result"),
        "quiz": orch.context.get("quiz"),
        "difficulty": orch.context.get("difficulty"),
    }


@app.post("/session/submit_answer")
def submit_answer(req: SubmitAnswerRequest):
    """
    Submits the student's answer to the current quiz question. Advances the
    loop through EVALUATE and either returns DONE, a new TEACH+QUIZ cycle
    (if the gap isn't closed yet), or a REPLAN escalation.
    """
    orch = _sessions.get(req.session_id)
    if not orch:
        raise HTTPException(status_code=404, detail="Session not found")

    orch.context["latest_student_response"] = req.student_response
    orch.step()  # runs EVALUATE

    response = {
        "session_id": req.session_id,
        "state": orch.state.name,
        "eval_result": orch.context.get("eval_result"),
        "current_mastery": orch.context.get("current_mastery"),
    }

    if orch.state == LoopState.TEACH:
        # Gap not closed — run the next teach+quiz cycle automatically
        while orch.state != LoopState.EVALUATE and orch.state != LoopState.DONE:
            orch.step()
        response["state"] = orch.state.name
        response["teach"] = orch.context.get("last_teach_result")
        response["quiz"] = orch.context.get("quiz")
        response["difficulty"] = orch.context.get("difficulty")

    elif orch.state == LoopState.REPLAN:
        orch.step()  # runs REPLAN
        response["state"] = orch.state.name
        response["replan_result"] = orch.context.get("replan_result")

    if orch.state == LoopState.DONE:
        del _sessions[req.session_id]  # session complete, free memory

    return response


@app.get("/session/{session_id}")
def get_session(session_id: str):
    orch = _sessions.get(session_id)
    if not orch:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"state": orch.state.name, "context": orch.context}


# ---------- Syllabus ingestion ----------

@app.post("/syllabus/from_text")
def syllabus_from_text(req: SyllabusTextRequest):
    """
    For a plain input box on the frontend — user pastes their syllabus as text.
    Parses it into the topic graph and overwrites syllabus_graph.json.
    """
    graph = parse_and_save(req.text)
    return {"status": "ok", "topics_extracted": len(graph), "graph": graph}


@app.post("/syllabus/from_file")
async def syllabus_from_file(file: UploadFile = File(...)):
    """
    For a file upload button. Accepts .txt directly; for .pdf/.docx you must
    extract text first (see note below) since this endpoint expects plain text.
    """
    if not file.filename.lower().endswith((".txt", ".md")):
        raise HTTPException(
            status_code=400,
            detail="Only .txt/.md accepted here. For PDF/DOCX, extract text "
                   "first (e.g. pdfplumber or python-docx) then call this "
                   "endpoint, or send extracted text to /syllabus/from_text.",
        )
    raw_bytes = await file.read()
    raw_text = raw_bytes.decode("utf-8", errors="ignore")
    graph = parse_and_save(raw_text)
    return {"status": "ok", "topics_extracted": len(graph), "graph": graph}


@app.get("/syllabus")
def get_syllabus():
    return _load_graph()


# ---------- Dashboard / analytics ----------

@app.get("/student/{student_id}/dashboard")
def dashboard(student_id: str):
    return get_dashboard_summary(student_id)


@app.get("/student/{student_id}/mastery_trend/{topic}")
def mastery_trend(student_id: str, topic: str, days: int = 30):
    return get_mastery_trend(student_id, topic, days=days)


@app.get("/student/{student_id}/mastery/{topic}")
def mastery(student_id: str, topic: str):
    return {"topic": topic, "mastery": get_mastery(student_id, topic)}


# ---------- Planning ----------

@app.post("/student/roadmap")
def roadmap(req: RoadmapRequest):
    return build_roadmap(
        student_id=req.student_id,
        mastery_map=req.mastery_map,
        days_remaining=req.days_remaining,
    )


# ---------- Student profile ----------

@app.get("/student/{student_id}/learning_style")
def learning_style(student_id: str):
    return {"learning_style": get_learning_style(student_id)}


@app.post("/student/learning_style")
def set_style(req: SetLearningStyleRequest):
    set_learning_style(req.student_id, req.style)
    return {"status": "ok"}


@app.get("/student/{student_id}/errors")
def get_errors(student_id: str):
    from memory_agent import get_recent_error_history
    return get_recent_error_history(student_id)


@app.post("/student/{student_id}/export_guide")
def export_study_guide(student_id: str):
    """
    Invokes the LLM to generate a customized Markdown study guide
    for the student's weakest topics and exports it directly to the workspace disk.
    """
    from progress_tracking_agent import get_dashboard_summary
    from groq_client import Groq
    import json
    
    summary = get_dashboard_summary(student_id)
    weakest = summary.get("weakest_topics", [])
    
    if not weakest:
        graph = _load_graph()
        topics_list = list(graph.keys())
        fallback_topic = topics_list[0] if topics_list else "general_study"
        weakest = [{"topic": fallback_topic, "mastery": 0.0}]
        
    prompt = f"""You are an Expert Study Guide Writer Agent.
Your job is to write a highly detailed and helpful study guide for a student who is struggling with specific topics.

We have identified their weakest topics and mastery scores:
{json.dumps(weakest, indent=2)}

Create a detailed Markdown study guide. For EACH topic listed:
1. Explain the concept clearly and concisely using a helpful, easy-to-understand modality (e.g. Worked Example or Analogy).
2. Provide a detailed step-by-step solved problem.
3. Provide one practice question for the student to solve on their own, along with the expected final answer.

Format the output cleanly in Markdown, beginning with a '# Personalized Study Guide' header and a friendly opening statement.
Do not wrap it in anything other than clean markdown. Avoid generic chat intro/outro outside of the markdown document itself.
"""

    client = Groq(api_key=os.environ.get("GROQ_API_KEY") or "MOCK_KEY")
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "You are a helpful educational assistant that outputs clean, detailed Markdown content."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
        )
        content = response.choices[0].message.content
        
        filename = f"{student_id}_study_guide.md"
        filepath = os.path.join(os.path.dirname(__file__), filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
            
        return {
            "status": "success",
            "filename": filename,
            "filepath": filepath,
            "message": f"Personalized study guide written to {filename}"
        }
    except Exception as e:
        filename = f"{student_id}_study_guide.md"
        filepath = os.path.join(os.path.dirname(__file__), filename)
        fallback_content = f"""# Personalized Study Guide for {student_id}

This is a fallback study guide. Please make sure to configure your `GROQ_API_KEY` in the `.env` file to generate a personalized guide.

## Weakest Topics to Review:
"""
        for t in weakest:
            fallback_content += f"- **{t['topic'].replace('_', ' ').title()}** (Current Mastery: {round(t['mastery']*100)}%)\n"
            
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(fallback_content)
            
        return {
            "status": "success",
            "filename": filename,
            "filepath": filepath,
            "message": f"Fallback study guide written to {filename} (Please configure GROQ_API_KEY for full guide)"
        }


@app.post("/student/{student_id}/generate_placement")
def generate_placement(student_id: str):
    """
    Generates a diagnostic test of exactly 10 questions covering topics in the active syllabus.
    """
    from curriculum_mapping_agent import _load_graph
    from groq import Groq
    import json
    
    graph = _load_graph()
    topics_list = list(graph.keys())
    
    if not topics_list:
        topics_list = ["linear_equations_isolation", "tcp_udp_reliability"]
        
    prompt = f"""You are an Expert Assessment Designer Agent.
Your job is to generate a diagnostic placement test of EXACTLY 10 questions to test a student's baseline knowledge.

Here is the list of topics in the active syllabus:
{json.dumps(topics_list)}

Generate exactly 10 questions. Distribute the questions across the topics. If there are fewer than 10 topics, create multiple different questions for the topics so that the total is EXACTLY 10.
Make the questions simple, clear, and direct (e.g., short-answer or math/logic problems that can be answered in a few words or lines).

Output ONLY a valid JSON object matching this schema, with no markdown wrappers or extra conversational text:
{{
  "test_id": "placement_{student_id}",
  "questions": [
    {{
      "question_id": 1,
      "topic": "<topic_id_matching_the_syllabus>",
      "question_text": "<clear question text>",
      "expected_answer": "<expected correct answer>"
    }}
  ]
}}
"""

    client = Groq(api_key=os.environ.get("GROQ_API_KEY") or "MOCK_KEY")
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "You are a specialized test designer agent that outputs ONLY valid JSON matching the specified schema."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
            response_format={"type": "json_object"},
        )
        data = json.loads(response.choices[0].message.content)
        _placement_tests[student_id] = data
        return data
    except Exception as e:
        print(f"[Placement Generation Fallback] LLM failed to generate placement test. Error: {e}")
        fallback_data = {
            "test_id": f"placement_{student_id}_fallback",
            "questions": []
        }
        for i in range(10):
            topic = topics_list[i % len(topics_list)]
            topic_clean = topic.replace("_", " ").title()
            fallback_data["questions"].append({
                "question_id": i + 1,
                "topic": topic,
                "question_text": f"Define and explain the core concept of {topic_clean}.",
                "expected_answer": f"A correct explanation of {topic_clean}."
            })
        _placement_tests[student_id] = fallback_data
        return fallback_data


@app.post("/student/{student_id}/submit_placement")
def submit_placement(student_id: str, req: SubmitPlacementRequest):
    """
    Submits student responses for the diagnostic placement test.
    Grades each response, logs them, and sets initial topic mastery scores.
    """
    from evaluator_agent import evaluate
    from memory_agent import update_mastery, log_error_event
    import json
    
    test = _placement_tests.get(student_id)
    if not test or test.get("test_id") != req.test_id:
        raise HTTPException(status_code=400, detail="Active placement test not found for this student.")
        
    results = []
    correct_count = 0
    
    for q in test["questions"]:
        q_id = q["question_id"]
        topic = q["topic"]
        expected = q["expected_answer"]
        student_ans = req.answers.get(str(q_id), req.answers.get(q_id, "")).strip()
        
        eval_res = evaluate(
            question=q["question_text"],
            rubric_or_expected_answer=expected,
            student_response=student_ans,
            target_skill=topic,
            current_mastery=0.5,
        )
        
        if isinstance(eval_res, list) and len(eval_res) > 0:
            eval_res = eval_res[0]
            
        is_correct = eval_res.get("is_correct", False)
        if is_correct:
            correct_count += 1
            update_mastery(student_id, topic, mastery_delta=0.3)
        else:
            update_mastery(student_id, topic, mastery_delta=-0.2)
            log_error_event(
                student_id=student_id,
                topic=topic,
                error_type=eval_res.get("error_classification", "conceptual"),
                meta={
                    "question": q["question_text"],
                    "student_answer": student_ans,
                    "correct_answer": expected
                }
            )
            
        results.append({
            "question_id": q_id,
            "topic": topic,
            "is_correct": is_correct,
            "score": eval_res.get("score", 0.0),
            "feedback": eval_res.get("feedback", "")
        })
        
    _placement_tests.pop(student_id, None)
    
    return {
        "status": "success",
        "total_questions": len(test["questions"]),
        "correct_answers": correct_count,
        "score_percentage": round((correct_count / len(test["questions"])) * 100),
        "results": results
    }


@app.get("/health")
def health():
    return {"status": "ok"}


# ---------- Developer / Seeding Endpoints ----------

@app.post("/dev/seed")
def seed_data(student_id: str = "student_001"):
    db = _session()
    try:
        # Clear existing data for this student
        db.query(ErrorEvent).filter_by(student_id=student_id).delete()
        db.query(TopicMastery).filter_by(student_id=student_id).delete()
        db.query(StudentProfile).filter_by(student_id=student_id).delete()

        # 1. Profile
        profile = StudentProfile(student_id=student_id, learning_style="worked_example")
        db.add(profile)

        # 2. Topic Mastery
        now_utc = datetime.now(timezone.utc)
        topics = [
            ("osi_model_basics", 0.85, 4, now_utc - timedelta(days=4)),
            ("arithmetic_operations", 0.95, 5, now_utc - timedelta(days=3)),
            ("inverse_operations", 0.75, 3, now_utc - timedelta(days=2)),
            ("tcp_udp_reliability", 0.35, 6, now_utc - timedelta(days=1)),
            ("linear_equations_isolation", 0.60, 2, now_utc),
            ("packet_switching", 0.45, 5, now_utc - timedelta(hours=6)),
        ]
        for topic, mastery, attempts, updated_at in topics:
            tm = TopicMastery(
                student_id=student_id,
                topic=topic,
                mastery=mastery,
                attempts=attempts,
                last_updated=updated_at
            )
            db.add(tm)

        # 3. Error Events (Historical timeline)
        events = [
            ("osi_model_basics", "conceptual", "worked_example", 0.6, 0.15, 4),
            ("osi_model_basics", "careless_slip", "worked_example", 0.9, 0.10, 4),
            ("arithmetic_operations", "procedural", "visual", 0.7, 0.20, 3),
            ("arithmetic_operations", "careless_slip", "visual", 1.0, 0.05, 3),
            ("inverse_operations", "prerequisite", "analogy", 0.4, -0.05, 2),
            ("inverse_operations", "conceptual", "analogy", 0.85, 0.25, 2),
            ("tcp_udp_reliability", "conceptual", "socratic", 0.2, -0.10, 1),
            ("tcp_udp_reliability", "conceptual", "worked_example", 0.45, 0.15, 1),
            ("linear_equations_isolation", "procedural", "visual", 0.3, -0.05, 0),
            ("linear_equations_isolation", "procedural", "worked_example", 0.75, 0.25, 0),
            ("packet_switching", "prerequisite", "socratic", 0.5, 0.10, 0),
        ]
        for topic, err, method, score, delta, days_ago in events:
            ev = ErrorEvent(
                student_id=student_id,
                topic=topic,
                error_type=err,
                method_used=method,
                score=score,
                mastery_delta=delta,
                timestamp=now_utc - timedelta(days=days_ago)
            )
            db.add(ev)

        db.commit()
        return {"status": "success", "message": f"Seeded rich historical data for {student_id}"}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        db.close()


@app.post("/dev/reset")
def reset_data(student_id: str = "student_001"):
    db = _session()
    try:
        db.query(ErrorEvent).filter_by(student_id=student_id).delete()
        db.query(TopicMastery).filter_by(student_id=student_id).delete()
        db.query(StudentProfile).filter_by(student_id=student_id).delete()
        db.commit()
        return {"status": "success", "message": f"Cleared all data for student {student_id}"}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        db.close()


# ---------- Frontend Serving ----------

@app.get("/", response_class=HTMLResponse)
def serve_frontend():
    static_path = os.path.join(os.path.dirname(__file__), "static", "index.html")
    if not os.path.exists(static_path):
        return HTMLResponse(
            content="<h1>Frontend not found</h1><p>Please create static/index.html first.</p>",
            status_code=404
        )
    with open(static_path, "r", encoding="utf-8") as f:
        content = f.read()
    return HTMLResponse(content=content)